apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inkpot-api-deployment
  name: inkpot-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inkpot-web-deployment
    spec:
      containers:
        - image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 8080
              protocol: TCP