apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inkpot-api-deployment
  name: inkpot-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inkpot-api-deployment
  template:
    metadata:
      labels:
        app: inkpot-api-deployment
    spec:
      containers:
        - image: eu.gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always
          name: inkpot-api-deployment
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /neo
              name: inkpot-pd
      volumes:
        - name: inkpot-pd
          persistentVolumeClaim:
            claimName: inkpot-pvc
