apiVersion: v1
kind: Service
metadata:
  name: inkpot-api
  labels:
    app: inkpot-api-deployment
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: inkpot-web-deployment